spring:
  datasource:
    url: jdbc:mysql://localhost:3306/madhub?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  # 服务地址
  endpoint: http://222.192.6.51:9099
  # 文件地址
  fileHost: http://222.192.6.51:9099
  # 存储桶名称
  bucket: madhub
  # 用户名
  access-key: minioadmin
  # 密码
  secret-key: minioadmin